### Importation des librairies nécessaires

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Importation du Dataset de tera_analytics

In [ ]:
df_tera = pd.read_csv("data/tera_analytics_data.csv", sep=",", header = 1)

### Première étude sur le dataset

In [ ]:
df_tera = pd.DataFrame(df_tera)
df_tera.head(10)

,id_sensor,id_install,time,longitude,latitude,pm1,pm25
0,100300037,H9V2,2024-02-20 07:12:51,47.108350,-21.437300,15.52,17.14
1,100300037,H9V2,2024-02-20 07:17:54,47.108330,-21.437310,6.10,6.62
2,100300037,H9V2,2024-02-20 07:22:57,47.108198,-21.437353,4.16,4.47
3,100300037,H9V2,2024-02-20 07:28:00,47.108247,-21.437353,4.01,4.25
4,100300037,H9V2,2024-02-20 07:33:03,47.108238,-21.437355,5.82,6.37
5,100300037,H9V2,2024-02-20 07:38:06,47.108148,-21.437302,3.36,3.57
6,100300037,H9V2,2024-02-20 07:43:09,47.108210,-21.437298,3.67,4.01
7,100300037,H9V2,2024-02-20 07:48:12,47.108288,-21.437267,32.00,37.94
8,100300037,H9V2,2024-02-20 07:53:14,47.108315,-21.437247,7.42,8.12
9,100300037,H9V2,2024-02-20 07:58:17,47.108320,-21.437225,4.34,4.65

### Informations sur les données

In [ ]:
df_tera.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1931158 entries, 0 to 1931157
Data columns (total 7 columns):
 #   Column      Dtype
---  ------      -----
 0   id_sensor   int64
 1   id_install  object
 2   time        object
 3   longitude   float64
 4   latitude    float64
 5   pm1         float64
 6   pm25        float64
dtypes: float64(4), int64(1), object(2)
memory usage: 103.1+ MB

In [ ]:
df_tera.describe()

          id_sensor     longitude      latitude           pm1          pm25
count  1.931158e+06  1.878131e+06  1.878131e+06  1.931158e+06  1.931158e+06
mean   1.003002e+08  4.710269e+01 -2.144821e+01  1.916398e+01  2.144862e+01
std    1.294235e+02  8.583174e-03  1.327915e-02  2.422881e+01  2.886623e+01
min    1.003000e+08  4.684618e+01 -2.157560e+01  0.000000e+00  0.000000e+00
25%    1.003001e+08  4.709643e+01 -2.146234e+01  5.450000e+00  5.870000e+00
50%    1.003001e+08  4.710618e+01 -2.145427e+01  1.234000e+01  1.353000e+01
75%    1.003003e+08  4.711009e+01 -2.143537e+01  2.421000e+01  2.690000e+01
max    1.003004e+08  4.713574e+01 -2.059398e+01  4.619800e+02  8.374800e+02

In [1]:
df_tera.shape

NameError: name 'df_tera' is not defined

In [8]:
for i in df_tera:
    print (df_tera[i].dtype )

int64
object
object
float64
float64
float64
float64

### Vérification des valeurs manquantes

In [9]:
df_tera.isna().sum()

id_sensor         0
id_install        0
time              0
longitude     53027
latitude      53027
pm1               0
pm25              0
dtype: int64

In [10]:
df_tera[df_tera.isna().any(axis=1)]

,id_sensor,id_install,time,longitude,latitude,pm1,pm25
744,100300037,H9V2,2024-02-22 03:27:00,NaN,NaN,1.73,1.82
868,100300216,E2VG,2024-02-22 08:44:33,NaN,NaN,6.10,6.41
1535,100300216,E2VG,2024-02-23 13:17:05,NaN,NaN,1.77,1.78
1781,100300037,H9V2,2024-02-23 23:38:52,NaN,NaN,2.93,3.12
2511,100300216,E2VG,2024-02-25 08:40:47,NaN,NaN,2.42,2.47
...,...,...,...,...,...,...,...
1931076,100300037,H9V2,2026-08-07 07:51:28,NaN,NaN,10.39,11.35
1931079,100300037,H9V2,2026-08-07 07:56:30,NaN,NaN,9.98,10.80
1931082,100300037,H9V2,2026-08-07 08:02:57,NaN,NaN,11.44,12.45
1931085,100300037,H9V2,2026-08-07 08:08:03,NaN,NaN,12.79,14.04
1931091,100300037,H9V2,2026-08-07 08:18:57,NaN,NaN,19.24,21.93

In [11]:
# Remplissage des valeurs manquantes des colonnes latitude et longitude
df_tera.replace(["N/A","null", "NULL", "None", "-", ""], np.nan)
df_tera = df_tera.dropna()

In [12]:
df_tera.isna().sum()

id_sensor     0
id_install    0
time          0
longitude     0
latitude      0
pm1           0
pm25          0
dtype: int64

### Vérifications des doublons

In [14]:
df_tera['id_sensor'].duplicated().sum()

np.int64(1878116)

In [ ]:
plt.figure(figsize= (6,4))
plt.plot(df_tera["pm25"], df_tera["pm1"])
plt.title("Graphique par pm1 par temps")
plt.xlabel("Temps")
plt.ylabel("pm1")
plt.show